import Search from '@/app/components/search'
import Footer from '@/app/components/footer'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Movies App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Search />
        {children}
        <Footer />
      </body>
    </html>
  )
}
